spring:
  application:
    name: api

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

youtube:
  api-token: test

ai-recipe-summary:
  url: test